language: node_js
node_js:
  - "node"
cache: 
  directories:
    - node_modules
services:
  - postgresql
  - redis-server
env:
  - NODE_ENV=test
before_script:
  - npm install
  - psql -c 'create database database_test;' -U postgres
script:
  - npm run test
notifications:
  email: false